### create new user and board
http://localhost:8080/user/getUserAndBoard/new_v1@test.com

> {%
    client.log("qwe");
    client.global.set("new_v1_boardId", response.body.boardId);
%}

### create new ticket
POST http://localhost:8080/ticketEntities
Content-Type: application/json;charset=UTF-8

{ "id": "7584407d-739f-43fa-98f5-3fdcb2322670", "boardId": "{{new_v1_boardId}}", "name": "Test ticket", "status": "BACKLOG" }

### Get tickets
http://localhost:8080/user/getUserAndBoard/new_v1@test.com

###