spring.profiles.active: local

---
spring.profiles: common

spring.jpa.properties.hibernate.dialect: com.enigmabridge.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto: create


---
spring.profiles: local
spring.profiles.include:
- common

spring.datasource.url: jdbc:sqlite:./db/localDb.db

---
spring.profiles: test
spring.profiles.include:
- common

spring.datasource.url: jdbc:sqlite:./target/localDb.db